# Generated by Django 2.2 on 2019-04-19 08:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2019, 4, 19, 8, 54, 4, 432084, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
