# Generated by Django 2.2 on 2019-04-26 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_auto_20190426_1710'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employer',
            options={'ordering': ('name',)},
        ),
        migrations.RemoveField(
            model_name='employer',
            name='alt_phone_no',
        ),
        migrations.RemoveField(
            model_name='employer',
            name='fax_number',
        ),
        migrations.RemoveField(
            model_name='employer',
            name='primary_phone_no',
        ),
    ]
