# Generated by Django 2.2 on 2019-04-26 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_auto_20190426_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='email',
            field=models.EmailField(max_length=500, null=True, verbose_name='Email'),
        ),
    ]
