# Generated by Django 2.2 on 2019-04-26 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='alt_phone_no',
            field=models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='Alternate Phone No'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='primary_phone_no',
            field=models.CharField(max_length=128, null=True, verbose_name='Phone No'),
        ),
    ]
