# Generated by Django 2.2 on 2019-04-25 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Core',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Changes done')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField()),
            ],
            options={
                'ordering': ('-updated_on', '-created_on'),
            },
        ),
    ]
