# Generated by Django 2.2 on 2019-04-26 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=500, null=True, verbose_name='Company name'),
        ),
        migrations.AlterField(
            model_name='company',
            name='registered_name',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Registered Company name'),
        ),
    ]
